### ISSUE TITLE
Auto generate .d.ts

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#159]
Rough notes:

- Provide a new crate named `napi-bindgen-rt` for `Rust` users.
- Provide a new macro in `napi-derive` named `bindgen`
- Convert `rust` types in `macro` and generate runtime codes:

```rust
use napi_bindgen_rt::Maybe;
use napi_derive::bindgen;

#[bindgen]
pub fn sum(x: u32, y: Maybe<Option<u32>>) -> u32 {
  x + y.unwrap_option_or(|| 0)
}
```

```ts
export function sum(x: number, y: number | undefined | null): number
```

## TODO

- [x] List Rust types => ts types convert table
- [x] What about async codes?
- [x] What about JsClass? Should we provide class bindgen like [PyO3](https://github.com/PyO3/pyo3) or [node-bindgen](https://github.com/infinyon/node-bindgen) ?
- [ ] What about Node.js builtin modules? Should we provide `node-sys` crate like `web-sys` in [wasm-bindgen](https://rustwasm.github.io/docs/wasm-bindgen/web-sys/index.html)

**Comment by williamluke4** [comment]
Is there anything I can do to help here?

**Comment by Brooooooklyn** [comment]
@williamluke4 I have written a quick notes below, it's some rough thoughts in my mind for now. If you are interesting in some points of these, you can start it now. If you need any help from me, feel free to ask here or open new discussions.

I've been very busy on my company's work for the last 2 months, and this situation may continue to June, so I don't have much time on OSS project during these days.

**Comment by yisibl** [comment]
Are we all done yet?

**Comment by Brooooooklyn** [comment]
It's almost done in `2.0` alpha version
